name: Despliegue Azure Web App

on:
  push:
    branches:
      - main  # cada vez que subas algo a main, se ejecuta

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Clona tu repo

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install
        working-directory: ./  # Busca package.json en la ra√≠z

      - name: Desplegar en Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
